# .octocov.yml Go example
coverage:
  paths:
    - todo-api/coverage.out
codeToTestRatio:
  code:
    - 'todo-api/**/*.go'
    - '!todo-api/**/*_test.go'
  test:
    - 'todo-api/**/*_test.go'
testExecutionTime:
  if: true
diff:
  datastores:
    - artifact://${GITHUB_REPOSITORY}
comment:
  if: is_pull_request
report:
  if: is_default_branch
  datastores:
    - artifact://${GITHUB_REPOSITORY}