name: test

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '>=1.19'
    - name: Check out code
      uses: actions/checkout@v3
    - name: Run Go tests
      run: go test ./... -coverprofile=coverage.out
      working-directory: todo-api
    - name: Report coverage
      uses: k1LoW/octocov-action@v0
